# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0002_ultimahora'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Youtube Slide',
                'verbose_name': 'Youtube Slide',
            },
        ),
        migrations.AlterModelOptions(
            name='ultimahora',
            options={'verbose_name': 'Ultima Hora', 'verbose_name_plural': 'Ultima hora'},
        ),
    ]
