# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0003_auto_20170104_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='slider')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.AlterModelOptions(
            name='youtubeslide',
            options={'verbose_name': 'Youtube Slider', 'verbose_name_plural': 'Youtube Slider'},
        ),
        migrations.AlterField(
            model_name='youtubeslide',
            name='imagen',
            field=models.ImageField(upload_to='sliderengine'),
        ),
    ]
