# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 14:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0006_auto_20170120_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('Caracas', 'Caracas'), ('Apure', 'Apure'), ('Barcelona', 'Barcelona'), ('Barinas', 'Barinas'), ('Barquisimento', 'Barquisimento'), ('Carupano', 'Carupano'), ('Ciudad Bolivar', 'Ciudad Bolivar'), ('Maracaibo', 'Maracaibo'), ('Maracay', 'Maracay'), ('Margarita', 'Margarita'), ('Maturin', 'Maturin'), ('Puerto Ayacucho', 'Puerto Ayacucho'), ('Punto Fijo', 'Punto Fijo'), ('San Cristobal', 'San Cristobal'), ('San Juan de los Morros', 'San Juan de los Morros')], max_length=60)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El numero debe telefono debe contener 15 caracteres', regex='^\\+?1?\\d{9, 15}$')])),
                ('direccion', models.CharField(max_length=250)),
                ('horario', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Militar')),
            ],
        ),
    ]
