# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_auto_20170123_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='noticias.Militar'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rango',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ran', to='noticias.Militar'),
        ),
    ]
