# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 14:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0009_auto_20170123_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('AA', 'Atencion al Afiliado'), ('FyU', 'Filiales y Unidades de Negocio'), ('GI', 'Gerencias Internas')], default='AA', max_length=3)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El Formato para ingresar el numero de teledono es xxxx-xxx.xx.xx Ejemplo 0212-855.23.30', regex='^(\\d{4})-(\\d{3}).(\\d{2}).(\\d{2})')])),
                ('direccion', models.CharField(max_length=250)),
                ('horario', models.CharField(max_length=250)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Militar')),
            ],
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='rango',
        ),
        migrations.AlterField(
            model_name='rango',
            name='rango',
            field=models.CharField(choices=[('G/F.', 'General en Jefe'), ('G/D.', 'General de Divicion'), ('G/B.', 'General de Brigada'), ('CNEL.', 'Coronel'), ('TCNEL.', 'Teniente Coronel'), ('MY.', 'Mayor'), ('CAP.', 'Capitan'), ('TTE.', 'Teniente'), ('AL.', 'Almirante'), ('V/A.', 'Vicealmirante'), ('C/A.', 'Contralmirante'), ('C/N.', 'Capitan de Navio'), ('C/F.', 'Capitan de Fragata'), ('C/C.', 'Capitan de Corbeta'), ('T/N.', 'Teniente de Navio'), ('T/F.', 'Teniente de Fragata')], max_length=6),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(choices=[('Caracas', 'Caracas'), ('Apure', 'Apure'), ('Barcelona', 'Barcelona'), ('Barinas', 'Barinas'), ('Barquisimento', 'Barquisimento'), ('Carupano', 'Carupano'), ('Ciudad Bolivar', 'Ciudad Bolivar'), ('Maracaibo', 'Maracaibo'), ('Maracay', 'Maracay'), ('Margarita', 'Margarita'), ('Maturin', 'Maturin'), ('Puerto Ayacucho', 'Puerto Ayacucho'), ('Punto Fijo', 'Punto Fijo'), ('San Cristobal', 'San Cristobal'), ('San Juan de los Morros', 'San Juan de los Morros'), ('Tucupita', 'Tucupita')], max_length=60),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El Formato para ingresar el numero de teledono es xxxx-xxx.xx.xx Ejemplo 0212-855.23.30', regex='^(\\d{4})-(\\d{3}).(\\d{2}).(\\d{2})')]),
        ),
    ]
