# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0010_auto_20170125_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=100, unique=True)),
                ('beneficio', models.CharField(max_length=100, unique=True)),
                ('texto', tinymce.models.HTMLField(verbose_name='Texto')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, upload_to='beneficios')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Beneficio')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'verbose_name': 'Gerencia', 'verbose_name_plural': 'Gerencias'},
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
