# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_auto_20170127_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='beneficiodocumento',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
