# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_auto_20170127_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='dep',
            field=models.CharField(choices=[('Af', 'Afiliacion'), ('BS', 'Bienestar y Seguridad Social'), ('BT', 'Beneficios del Trabajador'), ('Cr', 'Créditos'), ('SISA', 'SISA'), ('In', 'Inversora')], default='AA', max_length=4),
        ),
    ]
