# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_beneficio_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='dependencia',
        ),
    ]
