# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_auto_20170127_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='dependencia',
            field=models.CharField(choices=[('Afiliacion', 'Afiliacion'), ('Bienestar y Seguridad Social', 'Bienestar y Seguridad Social'), ('Beneficios del Trabajador', 'Beneficios del Trabajador'), ('Créditos', 'Créditos'), ('SISA', 'SISA'), ('Inversora', 'Inversora')], default='AA', max_length=100),
        ),
    ]
