# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0021_auto_20170208_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratacionesPublicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contrataciones Publicas',
                'verbose_name': 'Contrataciones Publicas',
            },
        ),
        migrations.RemoveField(
            model_name='carouselnota',
            name='titulo',
        ),
    ]
