# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0023_contratacionespublicas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionespublicas',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='contrataciones'),
        ),
    ]
