# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0025_auto_20170209_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efemerides',
            options={'verbose_name': 'Efemerides', 'verbose_name_plural': 'Efemerides'},
        ),
    ]
